# Generated by Django 6.0.1 on 2026-06-06 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the course or subject (e.g. Physiology).', max_length=150, verbose_name='Course Name')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': '2. Courses',
                'ordering': ['university__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(help_text="A short descriptive title for the case (e.g. 'A 45-year-old with chest pain').", max_length=200, verbose_name='Case Title')),
                ('case_description', models.TextField(help_text='Patient history, symptoms, lab results, and clinical findings.', verbose_name='Case Description')),
                ('hint_1', models.CharField(help_text='Shown after the first wrong attempt.', max_length=255, verbose_name='Hint 1')),
                ('hint_2', models.CharField(help_text='Shown after the second wrong attempt.', max_length=255, verbose_name='Hint 2')),
                ('correct_diagnosis', models.CharField(help_text='The final answer — the name of the disease or condition.', max_length=150, verbose_name='Correct Diagnosis')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this case from students without deleting it.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Diagnosis Case',
                'verbose_name_plural': '6. Diagnosis Game Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full official name of the university.', max_length=150, unique=True, verbose_name='University Name')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': '1. Universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the unit or chapter (e.g. Cardiovascular System).', max_length=150, verbose_name='Module Name')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='quiz.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': '3. Modules',
                'ordering': ['course__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.CharField(help_text="e.g. 'Lecture 1', 'Week 3', 'Introduction'", max_length=150, verbose_name='Lecture')),
                ('question_text', models.TextField(verbose_name='Question Text')),
                ('option_a', models.CharField(max_length=255, verbose_name='Option A')),
                ('option_b', models.CharField(max_length=255, verbose_name='Option B')),
                ('option_c', models.CharField(max_length=255, verbose_name='Option C')),
                ('option_d', models.CharField(max_length=255, verbose_name='Option D')),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1, verbose_name='Correct Answer')),
                ('explanation', models.TextField(blank=True, help_text='Shown to the student after a wrong answer. Explain why the correct option is right.', null=True, verbose_name='Medical Explanation')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.course', verbose_name='Course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.module', verbose_name='Module')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.university', verbose_name='University')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': '4. Question Bank (MCQ)',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='quiz.university', verbose_name='University'),
        ),
        migrations.CreateModel(
            name='SavedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_note', models.TextField(blank=True, help_text="The student's own study notes on this question.", null=True, verbose_name='Personal Note')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='Saved At')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_students', to='quiz.question', verbose_name='Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_notes', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Saved Note',
                'verbose_name_plural': '5. Student Saved Notes',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['university', 'course', 'module'], name='quiz_questi_univers_9a8e32_idx'),
        ),
    ]
