# Generated by Django 6.0.1 on 2026-06-06 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='e.g. Physiology, Anatomy, Pathology', max_length=150, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='diagnosiscase',
            name='case_description',
            field=models.TextField(verbose_name='Case Description'),
        ),
        migrations.AlterField(
            model_name='diagnosiscase',
            name='case_title',
            field=models.CharField(max_length=200, verbose_name='Case Title'),
        ),
        migrations.AlterField(
            model_name='diagnosiscase',
            name='correct_diagnosis',
            field=models.CharField(max_length=150, verbose_name='Correct Diagnosis'),
        ),
        migrations.AlterField(
            model_name='diagnosiscase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diagnosiscase',
            name='hint_1',
            field=models.CharField(max_length=255, verbose_name='Hint 1'),
        ),
        migrations.AlterField(
            model_name='diagnosiscase',
            name='hint_2',
            field=models.CharField(max_length=255, verbose_name='Hint 2'),
        ),
        migrations.AlterField(
            model_name='diagnosiscase',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(help_text='e.g. Cardiovascular System, Renal System', max_length=150, verbose_name='Module Name'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Shown after a wrong answer. Explain why the correct option is right.', null=True, verbose_name='Medical Explanation'),
        ),
        migrations.AlterField(
            model_name='savednote',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_students', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='savednote',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='savednote',
            name='student_note',
            field=models.TextField(blank=True, null=True, verbose_name='Personal Note'),
        ),
        migrations.AlterField(
            model_name='savednote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AINote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='The question/topic the student asked the AI about.', verbose_name='Original Prompt')),
                ('content', models.TextField(help_text='The summary or clinical notes returned by the AI.', verbose_name='AI-Generated Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Saved At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_notes', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'AI Note',
                'verbose_name_plural': '7. AI Notes (Medical Assistant)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='medium', max_length=10)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('tf', 'True / False'), ('case', 'Case Studies')], default='mcq', max_length=10)),
                ('specialties', models.JSONField(default=list, help_text='List of specialty strings selected by the student.')),
                ('show_explanations', models.BooleanField(default=True)),
                ('question_count', models.PositiveIntegerField(default=20)),
                ('question_pks', models.JSONField(default=list, help_text='Ordered list of Question PKs used in this attempt.')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_secs', models.PositiveIntegerField(blank=True, help_text='Total seconds the student spent on the quiz.', null=True)),
                ('time_limit_secs', models.PositiveIntegerField(default=1800, help_text='Timer limit in seconds.')),
                ('score_correct', models.PositiveIntegerField(default=0)),
                ('score_total', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': '8. Quiz Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Position of this question in the quiz (0-indexed).')),
                ('chosen_option', models.CharField(blank=True, help_text='The letter (A/B/C/D) the student chose. Null if unanswered (time ran out).', max_length=1, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='quiz.question')),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='quiz.quizattempt')),
            ],
            options={
                'verbose_name': 'Question Attempt',
                'verbose_name_plural': '9. Question Attempts',
                'ordering': ['quiz_attempt', 'order'],
                'unique_together': {('quiz_attempt', 'question')},
            },
        ),
    ]
