# Generated by Django 6.0.1 on 2026-06-06 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_course_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Year 1', 'Year 2', 'Year 3 Prep'.", max_length=50, unique=True, verbose_name='Academic Year Name')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': '2. Academic Years',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='ainote',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='questionattempt',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='questionattempt',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionattempt',
            name='quiz_attempt',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': '3. Courses'},
        ),
        migrations.AlterModelOptions(
            name='diagnosiscase',
            options={'verbose_name': 'Diagnosis Case', 'verbose_name_plural': '7. Diagnosis Cases (Future Feature)'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Module', 'verbose_name_plural': '4. Modules'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'MCQ Question', 'verbose_name_plural': '5. MCQ Questions'},
        ),
        migrations.AlterModelOptions(
            name='savednote',
            options={'verbose_name': 'Saved Bookmark', 'verbose_name_plural': '6. Saved Bookmarks'},
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='quiz_questi_univers_9a8e32_idx',
        ),
        migrations.AlterUniqueTogether(
            name='savednote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='diagnosiscase',
            name='hint_1',
        ),
        migrations.RemoveField(
            model_name='diagnosiscase',
            name='hint_2',
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French')], default='EN', max_length=2, verbose_name='Item Language'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='quiz.university'),
        ),
        migrations.AlterField(
            model_name='diagnosiscase',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='quiz.course'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Module Name'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1, verbose_name='Correct Answer Letter'),
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Educational Rationale'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lecture',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Lecture Reference Title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.module'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='Question Wording'),
        ),
        migrations.AlterField(
            model_name='question',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.university'),
        ),
        migrations.AlterField(
            model_name='savednote',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='savednote',
            name='student_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(help_text='Full official name of the university or training hospital.', max_length=150, unique=True, verbose_name='University Name'),
        ),
        migrations.AddField(
            model_name='course',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='quiz.academicyear'),
        ),
        migrations.AddField(
            model_name='question',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.academicyear'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='allowed_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.academicyear', verbose_name='Permitted Curriculum Year'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.university', verbose_name='Enrolled University'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AINote',
        ),
        migrations.DeleteModel(
            name='QuestionAttempt',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
