# Generated by Django 6.0.1 on 2026-06-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_academicyear_studentprofile_remove_ainote_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(help_text="Specify all correct letters separated by commas if multiple are true. Examples: 'A' or 'A,C' or 'A,B,D'.", max_length=20, verbose_name='Correct Option(s)'),
        ),
    ]
