# Generated by Django 6.0.1 on 2026-06-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_question_correct_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosiscase',
            options={'verbose_name': 'Diagnosis Game Case', 'verbose_name_plural': '6. Diagnosis Game Cases'},
        ),
        migrations.AddField(
            model_name='diagnosiscase',
            name='hint_1',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Hint Box 1: Secondary Clue'),
        ),
        migrations.AddField(
            model_name='diagnosiscase',
            name='hint_2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Hint Box 2: Lab Results / Biomarkers'),
        ),
        migrations.AddField(
            model_name='diagnosiscase',
            name='hint_3',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Hint Box 3: Imaging / EKG Findings'),
        ),
        migrations.AddField(
            model_name='diagnosiscase',
            name='hint_4',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Hint Box 4: Clinical Progression Detail'),
        ),
        migrations.AddField(
            model_name='diagnosiscase',
            name='hint_5',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Hint Box 5: Pathognomonic Physical Sign'),
        ),
        migrations.AddField(
            model_name='diagnosiscase',
            name='hint_6',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Hint Box 6: Final Definitive Clue'),
        ),
        migrations.AddField(
            model_name='diagnosiscase',
            name='prise_on_charge',
            field=models.TextField(blank=True, default='', help_text='The immediate pop-up guidance showing life-saving actions, medication guidelines, or surgical indications.', verbose_name='Prise en Charge (Treatment & Management)'),
        ),
        migrations.AddField(
            model_name='diagnosiscase',
            name='specialty_category',
            field=models.CharField(default='General Medicine', help_text="Broad filter parameter. Examples: 'Cardiologie', 'Neurologie', 'Gastro-entérologie'.", max_length=100, verbose_name='Medical Specialty'),
        ),
        migrations.AlterField(
            model_name='diagnosiscase',
            name='case_description',
            field=models.TextField(help_text='Baseline status shown to the doctor immediately on game launch (Vitals, primary complaint).', verbose_name='Initial Case Presentation'),
        ),
        migrations.AlterField(
            model_name='diagnosiscase',
            name='case_title',
            field=models.CharField(help_text="A short title (e.g., 'A 54-year-old presenting with sharp substernal distress').", max_length=200, verbose_name='Case Vignette Title'),
        ),
        migrations.AlterField(
            model_name='diagnosiscase',
            name='correct_diagnosis',
            field=models.CharField(help_text="The exact pathognomonic term. Example: 'Acute Myocardial Infarction' or 'Infarctus du myocarde'.", max_length=150, verbose_name='Correct Medical Term Diagnosis'),
        ),
        migrations.AlterField(
            model_name='diagnosiscase',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status Track'),
        ),
    ]
