# Generated by Django 6.0.1 on 2026-06-08 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_diagnosiscase_options_diagnosiscase_hint_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosiscase',
            options={'verbose_name': 'Diagnosis Game Case', 'verbose_name_plural': '7. Diagnosis Game Cases'},
        ),
        migrations.RemoveField(
            model_name='diagnosiscase',
            name='hint_1',
        ),
        migrations.RemoveField(
            model_name='diagnosiscase',
            name='hint_2',
        ),
        migrations.RemoveField(
            model_name='diagnosiscase',
            name='hint_3',
        ),
        migrations.RemoveField(
            model_name='diagnosiscase',
            name='hint_4',
        ),
        migrations.RemoveField(
            model_name='diagnosiscase',
            name='hint_5',
        ),
        migrations.RemoveField(
            model_name='diagnosiscase',
            name='hint_6',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_d',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(help_text="Specify the order number(s) of the correct option(s), separated by commas. Example: '1' for only the first option, or '1,3' if the first and third are both correct.", max_length=20, verbose_name='Correct Option(s)'),
        ),
        migrations.CreateModel(
            name='DiagnosisHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Reveal sequence (1 = shown after 1st wrong answer, 2 = after 2nd, …).', verbose_name='Hint Order')),
                ('label', models.CharField(blank=True, default='', help_text="Optional display title shown above the hint box, e.g. 'Lab Results' or 'EKG Findings'.", max_length=100, verbose_name='Hint Label')),
                ('text', models.CharField(max_length=512, verbose_name='Hint Text')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='quiz.diagnosiscase')),
            ],
            options={
                'verbose_name': 'Diagnosis Hint',
                'verbose_name_plural': 'Diagnosis Hints',
                'ordering': ['order'],
                'unique_together': {('case', 'order')},
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Display position (1 = first, 2 = second, …). Must be unique per question.', verbose_name='Option Order')),
                ('text', models.CharField(max_length=512, verbose_name='Option Text')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question')),
            ],
            options={
                'verbose_name': 'Question Option',
                'verbose_name_plural': 'Question Options',
                'ordering': ['order'],
                'unique_together': {('question', 'order')},
            },
        ),
    ]
