# Generated by Django 6.0.1 on 2026-06-09 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_diagnosiscase_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisCaseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hints_unlocked_count', models.PositiveSmallIntegerField(default=0)),
                ('is_solved', models.BooleanField(default=False)),
                ('attempts_count', models.PositiveSmallIntegerField(default=0)),
                ('needs_review', models.BooleanField(db_index=True, default=False, help_text='Auto-set to True when the student exhausts all 6 attempts without solving.', verbose_name='Needs Spaced-Repetition Review')),
                ('flagged', models.BooleanField(db_index=True, default=False, verbose_name='Manually Flagged by Student')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='quiz.diagnosiscase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnosis Case Progress',
                'verbose_name_plural': '9. Diagnosis Case Progress',
                'indexes': [models.Index(fields=['user', 'case'], name='idx_diagprogress_user_case'), models.Index(fields=['user', 'needs_review'], name='idx_diagprogress_needs_review')],
                'unique_together': {('user', 'case')},
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_indices', models.CharField(default='[]', max_length=64)),
                ('is_correct', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(db_index=True, default=False, help_text='Auto-set to True when the student answers incorrectly. Reset to False once they answer correctly in a review session.', verbose_name='Needs Spaced-Repetition Review')),
                ('flagged', models.BooleanField(db_index=True, default=False, help_text='Student-controlled bookmark — marks a question for intentional later review.', verbose_name='Manually Flagged by Student')),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quiz.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Answer',
                'verbose_name_plural': '8. User Answers (MCQ Progress)',
                'indexes': [models.Index(fields=['user', 'question'], name='idx_useranswer_user_question'), models.Index(fields=['user', 'needs_review'], name='idx_useranswer_needs_review')],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
