# Generated by Django 6.0.1 on 2026-06-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_diagnosiscaseprogress_useranswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosishint',
            options={'verbose_name': 'Diagnosis Hint', 'verbose_name_plural': 'Diagnosis Hints'},
        ),
        migrations.AlterModelOptions(
            name='questionoption',
            options={'verbose_name': 'Question Option', 'verbose_name_plural': 'Question Options'},
        ),
        migrations.AlterUniqueTogether(
            name='diagnosishint',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='questionoption',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False, help_text='Auto-set to True when the student answers incorrectly. Reset to False once they answer correctly.', verbose_name='Needs Spaced-Repetition Review'),
        ),
        migrations.RemoveField(
            model_name='diagnosishint',
            name='label',
        ),
        migrations.RemoveField(
            model_name='diagnosishint',
            name='order',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='order',
        ),
    ]
