# Generated by Django 6.0.1 on 2026-06-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_diagnosishint_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosishint',
            options={'ordering': ['order'], 'verbose_name': 'Diagnosis Hint', 'verbose_name_plural': 'Diagnosis Hints'},
        ),
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ['order'], 'verbose_name': 'Question Option', 'verbose_name_plural': 'Question Options'},
        ),
        migrations.AddField(
            model_name='diagnosishint',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text='1-based position. Hint with order=1 is revealed after the first wrong attempt.', verbose_name='Reveal Order'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text="1-based position of this option. Must match the numbers used in 'Correct Option(s)' on the question.", verbose_name='Display Order'),
        ),
    ]
