# Generated by Django 6.0.1 on 2026-06-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_diagnosishint_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosishint',
            options={'ordering': ['pk'], 'verbose_name': 'Diagnosis Hint', 'verbose_name_plural': 'Diagnosis Hints'},
        ),
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ['pk'], 'verbose_name': 'Question Option', 'verbose_name_plural': 'Question Options'},
        ),
        migrations.RemoveField(
            model_name='diagnosishint',
            name='order',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='order',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(help_text="Use letters or numbers, separated by commas — case-insensitive. Examples: 'A', 'a', 'A,C', 'a,c', '1', '1,3'. A = first option, B = second, C = third, and so on.", max_length=20, verbose_name='Correct Option(s)'),
        ),
    ]
