# Generated by Django 6.0.1 on 2026-06-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_diagnosishint_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='language',
        ),
        migrations.AddField(
            model_name='diagnosiscase',
            name='case_description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Initial Case Presentation (French)'),
        ),
        migrations.AddField(
            model_name='diagnosiscase',
            name='correct_diagnosis_fr',
            field=models.CharField(blank=True, help_text="French equivalent. Example: 'Infarctus du myocarde'.", max_length=150, null=True, verbose_name='Correct Diagnosis (French)'),
        ),
        migrations.AddField(
            model_name='diagnosiscase',
            name='prise_on_charge_fr',
            field=models.TextField(blank=True, default='', verbose_name='Management (French)'),
        ),
        migrations.AddField(
            model_name='diagnosishint',
            name='text_fr',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Hint Text (French)'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation (French)'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Question (French)'),
        ),
        migrations.AlterField(
            model_name='diagnosiscase',
            name='case_description',
            field=models.TextField(help_text='Baseline status shown to the doctor immediately on game launch (Vitals, primary complaint).', verbose_name='Initial Case Presentation (English)'),
        ),
        migrations.AlterField(
            model_name='diagnosiscase',
            name='correct_diagnosis',
            field=models.CharField(help_text="The exact term. Example: 'Acute Myocardial Infarction'.", max_length=150, verbose_name='Correct Diagnosis'),
        ),
        migrations.AlterField(
            model_name='diagnosiscase',
            name='prise_on_charge',
            field=models.TextField(blank=True, default='', verbose_name='Management (English)'),
        ),
        migrations.AlterField(
            model_name='diagnosishint',
            name='text',
            field=models.CharField(max_length=512, verbose_name='Hint Text (English)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(help_text="Use letters or numbers, separated by commas — case-insensitive. Examples: 'A', 'a', 'A,C', 'a,c', '1', '1,3'. A/1 = first option, B/2 = second, C/3 = third, and so on.", max_length=20, verbose_name='Correct Option(s)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation (English)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='Question (English)'),
        ),
    ]
