# Generated by Django 6.0.1 on 2026-06-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_remove_question_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='text_fr',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Option Text (French)'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='text',
            field=models.CharField(max_length=512, verbose_name='Option Text (English)'),
        ),
    ]
