"""
Django settings for medquiz_project project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================================================
# PRODUCTION SECURITY CONFIGURATIONS
# ==============================================================

# Uses environment variable on Render, falls back to fallback string locally
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-d!1l!o-4=ja)si6ggl@8-wj-m+n-mdl52*@$mx^k_^a+#i%=ve')

# Automatically sets to False on production unless explicitly overridden
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Allows your platform's dynamic domains (.vercel.app or .koyeb.app) as well as local tests
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'quiz', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Added to host CSS/JS assets on Render safely
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'medquiz_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medquiz_project.wsgi.application'


# ==============================================================
# DATABASE ROUTING LOGIC
# ==============================================================

# Connects to Render's live PostgreSQL container if running online; otherwise defaults to SQLite locally
if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600, ssl_require=True)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Algiers'
USE_I18N = True
USE_TZ = True


# ==============================================================
# STATIC ASSETS & AUTH REDIRECTS MANAGEMENT
# ==============================================================

STATIC_URL = 'static/'

# Absolute directory location where Django dumps compiled global asset bundles during deployment
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Extra storage path spaces for lookup resolution engines if you use custom directory trees
STATICFILES_DIRS = [
    # BASE_DIR / 'static',  # Uncomment this only if you create a main "static" directory at project root
]

# Configure WhiteNoise engine compression cache properties
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

LOGIN_REDIRECT_URL = 'quiz:dashboard'